### PR TITLE
Wrong toString conversion

### PR DESCRIPTION
**Pull request by westtrade**

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Could you add a description to your PR? I have no clue what problem you are trying to solve.

**Comment by westtrade** [comment]
Problem occurs when duo returns result. As example with koajs bundle in next case
https://github.com/koajs/bundle

``` js

var bundle = Bundle(function *(file) {
  let result =  yield Duo(file.root)
    .entry(file.path)
    .use(require('duo-sass')())
    .run();

 return result;
})
app.use(bundle('app.css'));

```

in app.css returns [Object object]. Of course result can be used in the next way

``` js
return result.code;
```

but this way is not obvious and, i think, it would be better if the conversion to string will return packed result string.

**Comment by dominicbarnes** [comment]
This is just part of the API, it returns an object like `{ code, map }`, it's a pretty common practice. (Babel is the first example that comes to mind) `code` is the source code as you've identified. In addition, the `map` has the source map if you've enabled it for your build. You need to factor both in when building a string.

**Comment by dominicbarnes** [comment]
I'm going to close this PR, as simply returning `pack.code` is not a robust solution. I'd take a look at duo core to see how it uses the returned `{ code, map }` object.

**Update:** [here](https://github.com/duojs/duo/blob/0f0f83ce44858e77a38e9f441502114f8a93e95e/bin/_duo#L238-L242)'s some relevant code in the duo CLI.

**Pull request closed without merging**
